name: Build and Publish Docker Package
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['16']
    name: Build using Node v${{ matrix.node-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install and Build
        working-directory: api
        run: |
          yarn install
          yarn build
        env:
          CI: true
  
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['16']
    name: Test using Node v${{ matrix.node-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install and Build
        working-directory: api
        run: |
          yarn install
          yarn build
        env:
          CI: true
    
  publish:
    needs: [build, test]
    runs-on: ubuntu-latest
    name: Publish image to Github Packages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Publish image to Github Packages
        uses: docker/build-push-action@v2
        with:
          username: $GITHUB_ACTOR
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: kbve/api.kbve.com/api.kbve.com
          tag_with_sha: true
          tag_with_ref: true
  
